use crate::autoinstall::hash_password;
use crate::config::InjectConfig;
use crate::error::EngineResult;

use super::cidr::parse_cidr;

/// Append the Kickstart header (everything before `%packages`) to `lines`.
/// This is the directive list: locale/keyboard/timezone, root account,
/// optional user + SSH keys, network config, hostname, storage layout,
/// reboot, and the `firewall` directive.
pub(super) fn append_header(cfg: &InjectConfig, lines: &mut Vec<String>) -> EngineResult<()> {
    // ── Header ───────────────────────────────────────────────────────────────
    lines.push("# Generated by ForgeISO".to_string());
    lines.push("text".to_string());

    // ── Locale / keyboard / timezone ─────────────────────────────────────────
    let locale = cfg.locale.as_deref().unwrap_or("en_US.UTF-8");
    lines.push(format!("lang {locale}"));

    let kb = cfg.keyboard_layout.as_deref().unwrap_or("us");
    lines.push(format!("keyboard {kb}"));

    let tz = cfg.timezone.as_deref().unwrap_or("UTC");
    lines.push(format!("timezone {tz} --utc"));

    // ── Root account (locked) ─────────────────────────────────────────────────
    lines.push("rootpw --lock".to_string());

    // ── User account ─────────────────────────────────────────────────────────
    if let Some(uname) = &cfg.username {
        let mut user_line = format!("user --name={uname}");
        if !cfg.user.groups.is_empty() {
            user_line.push_str(&format!(" --groups={}", cfg.user.groups.join(",")));
        }
        if let Some(pwd) = &cfg.password {
            let hashed = hash_password(pwd)?;
            user_line.push_str(&format!(" --password={hashed} --iscrypted"));
        }
        if let Some(realname) = &cfg.realname {
            user_line.push_str(&format!(" --gecos=\"{realname}\""));
        }
        lines.push(user_line);

        // SSH authorized keys (one sshkey directive per key)
        for key in &cfg.ssh.authorized_keys {
            let k = key.trim();
            if !k.is_empty() {
                lines.push(format!("sshkey --username={uname} \"{k}\""));
            }
        }
    }

    // ── Network ──────────────────────────────────────────────────────────────
    if let Some(static_ip) = &cfg.static_ip {
        // Parse CIDR notation: "10.0.0.5/24" → ip=10.0.0.5 netmask=255.255.255.0
        let (ip, mask) = parse_cidr(static_ip);
        let mut net_line = format!(
            "network --bootproto=static --device=link --onboot=on --ip={ip} --netmask={mask}"
        );
        if let Some(gw) = &cfg.gateway {
            net_line.push_str(&format!(" --gateway={gw}"));
        }
        if !cfg.network.dns_servers.is_empty() {
            net_line.push_str(&format!(
                " --nameserver={}",
                cfg.network.dns_servers.join(",")
            ));
        }
        lines.push(net_line);
    } else {
        let mut net_line = "network --bootproto=dhcp --device=link --onboot=on".to_string();
        if !cfg.network.dns_servers.is_empty() {
            net_line.push_str(&format!(
                " --nameserver={}",
                cfg.network.dns_servers.join(",")
            ));
        }
        lines.push(net_line);
    }

    // ── Hostname ─────────────────────────────────────────────────────────────
    if let Some(hostname) = &cfg.hostname {
        lines.push(format!("network --hostname={hostname}"));
    }

    // ── Storage layout ───────────────────────────────────────────────────────
    match cfg.storage_layout.as_deref() {
        Some("lvm") => {
            lines.push("autopart --type=lvm".to_string());
        }
        Some("zfs") => {
            // Kickstart doesn't natively support ZFS; fall back to lvm
            lines.push("autopart --type=lvm".to_string());
        }
        _ => {
            lines.push("autopart --type=plain".to_string());
        }
    }
    lines.push("clearpart --all --initlabel".to_string());

    // ── Reboot ───────────────────────────────────────────────────────────────
    lines.push("reboot".to_string());

    // ── Firewall (native Kickstart directive) ─────────────────────────────────
    // The `firewall` directive controls the initial firewalld state at install
    // time.  Fine-grained port rules are applied in %post via firewall-cmd.
    if cfg.firewall.enabled {
        lines.push("firewall --enabled".to_string());
    } else {
        lines.push("firewall --disabled".to_string());
    }

    // ── repo directives (DNF extra repos) ────────────────────────────────────
    // Each entry is either a plain https:// URL (we emit a dnf install command
    // in %post) or a [id]\nbaseurl=... stanza pasted verbatim.  URL-only entries
    // are handled in %post; stanza entries go into a .repo file.
    // We emit nothing here in the header — dnf repos are consumed in %post.

    Ok(())
}

/// Append the Kickstart `%packages` block.
pub(super) fn append_packages(cfg: &InjectConfig, lines: &mut Vec<String>) {
    lines.push(String::new());
    lines.push("%packages".to_string());
    lines.push("@^minimal-environment".to_string());
    if cfg.firewall.enabled {
        lines.push("firewalld".to_string());
    }
    for pkg in &cfg.extra_packages {
        lines.push(pkg.clone());
    }
    lines.push("%end".to_string());
}
