//! Kickstart (`kickstart.cfg`) generator for the Fedora / RHEL family
//! (Fedora Server, Fedora Workstation, Rocky Linux, AlmaLinux,
//! CentOS Stream).
//!
//! Public entry point is [`generate_kickstart_cfg`] (re-exported at
//! the crate root). Sibling generators for other distro families:
//!
//! - [`crate::autoinstall`] — Ubuntu (`autoinstall.yaml`).
//! - [`crate::mint_preseed`] — Debian / Mint (`preseed.cfg`).
//!
//! See [`ADR 0005`](https://github.com/Al-Sarraf-Tech/ForgeISO/blob/main/docs/adr/0005-iso-injection-strategy.md)
//! for why the project ships per-distro generators rather than a
//! single overlay format.

use crate::config::InjectConfig;
use crate::error::EngineResult;

mod cidr;
mod header;
mod post;

// Re-exports preserve the original public surface at `crate::kickstart::*`.
pub(crate) use cidr::parse_cidr;

/// Generate a Fedora/RHEL Kickstart configuration from InjectConfig.
///
/// The resulting `ks.cfg` content covers identity, network, packages, and a
/// `%post` section that reuses the same late-command logic as the Ubuntu
/// cloud-init path (NTP, groups, shell, sudo, services, sysctl, swap,
/// firewall, GRUB, mounts, run_commands, extra_late_commands).
pub fn generate_kickstart_cfg(cfg: &InjectConfig) -> EngineResult<String> {
    let mut lines: Vec<String> = Vec::new();

    header::append_header(cfg, &mut lines)?;
    header::append_packages(cfg, &mut lines);
    post::append_post(cfg, &mut lines)?;

    Ok(lines.join("\n") + "\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{InjectConfig, IsoSource};

    fn base_cfg() -> InjectConfig {
        InjectConfig {
            source: IsoSource::from_raw("/tmp/fedora.iso"),
            out_name: "out.iso".to_string(),
            ..Default::default()
        }
    }

    #[test]
    fn test_kickstart_minimal() {
        let cfg = base_cfg();
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("# Generated by ForgeISO"));
        assert!(ks.contains("rootpw --lock"));
        assert!(ks.contains("reboot"));
        assert!(ks.contains("%packages"));
        assert!(ks.contains("%end"));
    }

    #[test]
    fn test_kickstart_with_user() {
        let mut cfg = base_cfg();
        cfg.username = Some("admin".to_string());
        cfg.password = Some("secret".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("user --name=admin"));
        assert!(ks.contains("--iscrypted"));
    }

    #[test]
    fn test_kickstart_with_static_ip() {
        let mut cfg = base_cfg();
        cfg.static_ip = Some("10.0.0.5/24".to_string());
        cfg.gateway = Some("10.0.0.1".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("--bootproto=static"));
        assert!(ks.contains("--ip=10.0.0.5"));
        assert!(ks.contains("--netmask=255.255.255.0"));
        assert!(ks.contains("--gateway=10.0.0.1"));
    }

    #[test]
    fn test_kickstart_packages() {
        let mut cfg = base_cfg();
        cfg.extra_packages = vec!["curl".to_string(), "git".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("curl"));
        assert!(ks.contains("git"));
    }

    #[test]
    fn test_cidr_parsing() {
        assert_eq!(
            parse_cidr("192.168.1.10/24"),
            ("192.168.1.10".to_string(), "255.255.255.0".to_string())
        );
        assert_eq!(
            parse_cidr("10.0.0.1/16"),
            ("10.0.0.1".to_string(), "255.255.0.0".to_string())
        );
    }

    #[test]
    fn test_kickstart_with_dnf_mirror() {
        let mut cfg = base_cfg();
        cfg.dnf_mirror = Some("https://mirror.example.com/fedora".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // dnf_mirror should appear in the generated kickstart
        assert!(
            ks.contains("mirror.example.com"),
            "dnf_mirror not found in kickstart: {ks}"
        );
    }

    #[test]
    fn test_kickstart_post_section_with_commands() {
        // %post is only emitted when there are late commands
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["echo hello".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // With run_commands, %post must be present
        assert!(
            ks.contains("%post"),
            "no %post section in kickstart when run_commands present"
        );
        assert!(ks.contains("%end"), "no %end after %post");
        assert!(ks.contains("echo hello"), "run_command missing from %post");
    }

    #[test]
    fn test_kickstart_services() {
        let mut cfg = base_cfg();
        cfg.enable_services = vec!["sshd".to_string(), "docker".to_string()];
        cfg.disable_services = vec!["firewalld".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // Services are emitted via systemctl in %post (not the Kickstart `services`
        // directive); each service generates its own line.
        assert!(
            ks.contains("systemctl enable sshd"),
            "enable sshd not found in kickstart %post: {ks}"
        );
        assert!(
            ks.contains("systemctl enable docker"),
            "enable docker not found in kickstart %post: {ks}"
        );
        assert!(
            ks.contains("systemctl disable firewalld"),
            "disable firewalld not found in kickstart %post: {ks}"
        );
    }

    #[test]
    fn test_kickstart_rpm_url_uppercase_extension() {
        // Regression: .RPM (uppercase) must be installed with `dnf install`,
        // NOT added as a repo with `dnf config-manager --add-repo`.
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["https://example.com/package.RPM".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("dnf install -y 'https://example.com/package.RPM'"),
            "uppercase .RPM URL must use 'dnf install', not 'dnf config-manager': {ks}"
        );
        assert!(
            !ks.contains("config-manager"),
            "uppercase .RPM URL must not use dnf config-manager: {ks}"
        );
    }

    #[test]
    fn test_kickstart_repo_url_install() {
        // Plain .rpm URLs should use dnf install
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["https://example.com/package.rpm".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("dnf install"),
            "rpm URL should use dnf install: {ks}"
        );
    }

    #[test]
    fn test_kickstart_repo_stanza_inline() {
        // Non-URL entries should be written as .repo stanza content
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["[myrepo]\nbaseurl=https://example.com/repo\nenabled=1".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("forgeiso-extra-0.repo") || ks.contains("myrepo"),
            "repo stanza should be written to a file: {ks}"
        );
    }

    #[test]
    fn test_repo_stanza_written_with_real_newlines() {
        // Regression: {stanza:?} (Debug formatting) was used, which escapes \n
        // as two-char sequences. The .repo file would then contain literal \n
        // characters instead of newlines, making the file unparseable by dnf.
        // Fix: use a heredoc so newlines are preserved verbatim.
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["[myrepo]\nbaseurl=https://example.com/repo\nenabled=1".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // The heredoc sentinel must appear as a line in %post
        assert!(
            ks.contains("FORGEISO_REPO_EOF"),
            "heredoc sentinel not found — stanza not written via heredoc: {ks}"
        );
        // The stanza body must appear verbatim (not as an escaped string)
        assert!(
            ks.contains("[myrepo]"),
            "repo stanza section header missing from kickstart: {ks}"
        );
        assert!(
            ks.contains("baseurl=https://example.com/repo"),
            "repo baseurl missing from kickstart: {ks}"
        );
        // Must NOT contain the debug-formatted backslash-n literal
        assert!(
            !ks.contains(r"[myrepo]\nbaseurl"),
            "stanza written with Debug-escaped \\n instead of real newlines: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_does_not_corrupt_bare_commands() {
        // A bare echo/printf command that happens to contain the substring
        // "/target" in a path literal must NOT be altered by the chroot
        // transformer (regression for the unwrap_or bug).
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["echo /data/target/file".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // The path must survive unchanged — only "chroot /target " prefix
        // commands are rewritten.
        assert!(
            ks.contains("/data/target/file"),
            "bare command with /target literal was incorrectly transformed: {ks}"
        );
        // And it must NOT appear without the /data prefix
        assert!(
            !ks.contains("echo /data//file"),
            "path was double-collapsed: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_rewrites_chroot_commands() {
        // Engine-generated "chroot /target ..." commands must be stripped of
        // their prefix with /target/ references resolved to /.
        // We trigger the transformer via enable_services which generates
        // "chroot /target systemctl enable sshd".
        let mut cfg = base_cfg();
        cfg.enable_services = vec!["sshd".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // chroot prefix removed; command appears directly in %post
        assert!(
            ks.contains("systemctl enable sshd"),
            "chroot command was not correctly stripped: {ks}"
        );
        // The "chroot /target " prefix must be absent
        assert!(
            !ks.contains("chroot /target systemctl enable sshd"),
            "chroot prefix not removed from generated service command: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_user_run_commands_untouched() {
        // User-provided run_commands must pass through unchanged even when they
        // contain /target path literals — the user controls their own paths and
        // may have intentional /target/ references in their scripts.
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["echo /data/target/archive.tar.gz".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("echo /data/target/archive.tar.gz"),
            "user run_command path was incorrectly rewritten: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_ntp_no_target_prefix_in_kickstart() {
        // Regression: NTP late-command writes to /target/etc/systemd/timesyncd.conf
        // in the cloud-init form.  In Kickstart %post (which runs inside the chroot),
        // that path must be rewritten to /etc/systemd/timesyncd.conf.
        let mut cfg = base_cfg();
        cfg.network = crate::config::NetworkConfig {
            ntp_servers: vec!["time.cloudflare.com".to_string()],
            dns_servers: vec![],
        };
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            !ks.contains("/target/etc/systemd/timesyncd.conf"),
            "NTP command still contains /target/ prefix in Kickstart output: {ks}"
        );
        assert!(
            ks.contains("/etc/systemd/timesyncd.conf"),
            "NTP config path missing from Kickstart %post: {ks}"
        );
        assert!(
            ks.contains("time.cloudflare.com"),
            "NTP server missing from Kickstart %post: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_proxy_no_target_prefix_in_kickstart() {
        // Regression: proxy late-commands write to /target/etc/environment.
        // In Kickstart %post, that path must be /etc/environment.
        let mut cfg = base_cfg();
        cfg.proxy = crate::config::ProxyConfig {
            http_proxy: Some("http://proxy.corp:3128".to_string()),
            https_proxy: None,
            no_proxy: vec![],
        };
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            !ks.contains("/target/etc/environment"),
            "proxy command still contains /target/ in Kickstart output: {ks}"
        );
        assert!(
            ks.contains("/etc/environment"),
            "proxy config path missing from Kickstart %post: {ks}"
        );
        assert!(
            ks.contains("http_proxy"),
            "http_proxy missing from Kickstart %post: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_sysctl_no_target_prefix_in_kickstart() {
        // Regression: sysctl late-commands write to /target/etc/sysctl.d/...
        // In Kickstart %post that path must be /etc/sysctl.d/...
        let mut cfg = base_cfg();
        cfg.sysctl = vec![("net.ipv4.ip_forward".to_string(), "1".to_string())];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            !ks.contains("/target/etc/sysctl.d"),
            "sysctl command still contains /target/ prefix in Kickstart output: {ks}"
        );
        assert!(
            ks.contains("/etc/sysctl.d/99-forgeiso.conf"),
            "sysctl config path missing from Kickstart %post: {ks}"
        );
    }

    #[test]
    fn test_kickstart_grub_uses_grub2_mkconfig_not_update_grub() {
        // Regression: build_feature_late_commands emitted "chroot /target update-grub"
        // unconditionally.  update-grub is a Debian/Ubuntu wrapper that does not exist
        // on Fedora.  For Fedora Kickstart %post, the correct command is
        // grub2-mkconfig -o /boot/grub2/grub.cfg.
        let mut cfg = base_cfg();
        cfg.distro = Some(crate::config::Distro::Fedora);
        cfg.grub = crate::config::GrubConfig {
            timeout: Some(5),
            cmdline_extra: vec![],
            default_entry: None,
        };
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("grub2-mkconfig"),
            "Fedora kickstart must use grub2-mkconfig, not update-grub: {ks}"
        );
        assert!(
            !ks.contains("update-grub"),
            "update-grub must not appear in Fedora kickstart (Debian-only): {ks}"
        );
    }

    #[test]
    fn test_post_transformer_grub_sed_no_target_prefix_in_kickstart() {
        // Regression: GRUB late-commands use `sed -i '...' /target/etc/default/grub`.
        // In Kickstart %post the path must be /etc/default/grub.
        let mut cfg = base_cfg();
        cfg.grub = crate::config::GrubConfig {
            timeout: Some(5),
            cmdline_extra: vec![],
            default_entry: None,
        };
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            !ks.contains("/target/etc/default/grub"),
            "GRUB sed command still contains /target/ prefix in Kickstart output: {ks}"
        );
        assert!(
            ks.contains("/etc/default/grub"),
            "GRUB config path missing from Kickstart %post: {ks}"
        );
    }
}
