//! Phase A of `inject_autoinstall`: generate distro-specific autoinstall
//! configs and write them into the workspace before the ISO is extracted.
//!
//! Each function returns nothing on success and emits engine events as
//! a side effect via the supplied `ForgeIsoEngine`.

use std::path::Path;

use crate::autoinstall::{generate_autoinstall_yaml, merge_autoinstall_yaml};
use crate::config::InjectConfig;
use crate::error::{EngineError, EngineResult};
use crate::events::{EngineEvent, EventPhase};
use crate::kickstart::generate_kickstart_cfg;
use crate::mint_preseed::generate_mint_preseed;

use crate::orchestrator::helpers::build_archinstall_config;
use crate::orchestrator::ForgeIsoEngine;

/// Ubuntu — write cloud-init `nocloud` overlay (user-data + meta-data).
pub(super) fn ubuntu(
    engine: &ForgeIsoEngine,
    cfg: &InjectConfig,
    work_dir: &Path,
) -> EngineResult<()> {
    let nocloud_dir = work_dir.join("overlay").join("nocloud");
    std::fs::create_dir_all(&nocloud_dir)?;

    let user_data = match &cfg.autoinstall_yaml {
        Some(path) => {
            let existing = std::fs::read_to_string(path)?;
            merge_autoinstall_yaml(&existing, cfg)?
        }
        None => generate_autoinstall_yaml(cfg)?,
    };
    std::fs::write(nocloud_dir.join("user-data"), &user_data)?;
    std::fs::write(nocloud_dir.join("meta-data"), "")?;

    engine.emit(EngineEvent::info(
        EventPhase::Inject,
        "created cloud-init overlay",
    ));
    Ok(())
}

/// Mint — Calamares-compatible preseed.cfg.
pub(super) fn mint(
    engine: &ForgeIsoEngine,
    cfg: &InjectConfig,
    work_dir: &Path,
) -> EngineResult<()> {
    // Mint uses Calamares (live desktop installer), not cloud-init.  Calamares
    // supports Debian-style preseed files for unattended installs when booted
    // with: `auto=true priority=critical preseed/file=/cdrom/preseed.cfg`.
    engine.emit(EngineEvent::warn(
        EventPhase::Inject,
        "Linux Mint uses Calamares — injecting preseed.cfg (NOT cloud-init autoinstall)",
    ));
    let preseed = generate_mint_preseed(cfg)?;
    std::fs::write(work_dir.join("preseed.cfg"), &preseed)?;

    engine.emit(EngineEvent::info(
        EventPhase::Inject,
        "generated preseed.cfg for Calamares",
    ));
    Ok(())
}

/// Fedora — Kickstart `ks.cfg`.
pub(super) fn fedora(
    engine: &ForgeIsoEngine,
    cfg: &InjectConfig,
    work_dir: &Path,
) -> EngineResult<()> {
    let ks_content = generate_kickstart_cfg(cfg)?;
    std::fs::write(work_dir.join("ks.cfg"), &ks_content)?;

    engine.emit(EngineEvent::info(
        EventPhase::Inject,
        "generated Kickstart ks.cfg",
    ));
    Ok(())
}

/// Arch — archinstall JSON config + launcher shell script.
pub(super) fn arch(
    engine: &ForgeIsoEngine,
    cfg: &InjectConfig,
    work_dir: &Path,
) -> EngineResult<()> {
    // Warn about features that cannot be expressed in an archinstall
    // JSON config.  These are silently dropped; the user should be
    // informed so they are not surprised by missing post-install state.
    let arch_unsupported: &[(&str, bool)] = &[
        ("swap", cfg.swap.is_some()),
        ("mounts", !cfg.mounts.is_empty()),
        ("sysctl", !cfg.sysctl.is_empty()),
        (
            "proxy",
            cfg.proxy.http_proxy.is_some() || cfg.proxy.https_proxy.is_some(),
        ),
        ("firewall", cfg.firewall.enabled),
        (
            "grub settings",
            cfg.grub.timeout.is_some()
                || !cfg.grub.cmdline_extra.is_empty()
                || cfg.grub.default_entry.is_some(),
        ),
        ("pacman_mirror", cfg.pacman_mirror.is_some()),
        ("pacman_repos", !cfg.pacman_repos.is_empty()),
        ("disable_services", !cfg.disable_services.is_empty()),
        ("run_commands", !cfg.run_commands.is_empty()),
        ("extra_late_commands", !cfg.extra_late_commands.is_empty()),
        ("apt_repos", !cfg.apt_repos.is_empty()),
    ];
    for (feature, active) in arch_unsupported {
        if *active {
            engine.emit(EngineEvent::warn(
                EventPhase::Inject,
                format!(
                    "Arch Linux: '{feature}' is not supported by archinstall config \
                     and will be ignored — configure it manually post-install"
                ),
            ));
        }
    }

    let archinstall_cfg = build_archinstall_config(cfg)?;
    let json_content = serde_json::to_string_pretty(&archinstall_cfg)
        .map_err(|e| EngineError::Runtime(e.to_string()))?;
    std::fs::write(work_dir.join("archinstall-config.json"), &json_content)?;

    // Create the run-archinstall.sh launcher script
    let launcher = concat!(
        "#!/usr/bin/env bash\n",
        "# Generated by ForgeISO -- triggers archinstall in unattended mode\n",
        "set -euo pipefail\n",
        "CONFIG=\"/run/archiso/bootmnt/arch/boot/archinstall-config.json\"\n",
        "if [[ -f \"${CONFIG}\" ]]; then\n",
        "    archinstall --config \"${CONFIG}\" --silent\n",
        "else\n",
        "    echo \"ERROR: archinstall config not found at ${CONFIG}\" >&2\n",
        "    exit 1\n",
        "fi\n"
    );
    std::fs::write(work_dir.join("run-archinstall.sh"), launcher)?;

    engine.emit(EngineEvent::info(
        EventPhase::Inject,
        "generated archinstall config",
    ));
    Ok(())
}
