use super::preset::IsoPreset;
use super::preset_id::PresetId;
use super::strategy::AcquisitionStrategy;

pub(super) static ALL_PRESETS: &[IsoPreset] = &[
    // ── Ubuntu (all via mirror.xenyth.net/ubuntu-releases) ───────────────────
    IsoPreset {
        id: PresetId::UbuntuServerLts,
        name: "Ubuntu 24.04.4 LTS Server",
        distro: "ubuntu",
        edition: "server-lts",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/24.04.4/ubuntu-24.04.4-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/noble/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 24.04.4 LTS Server (Noble) — unattended via cloud-init autoinstall",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktopLts,
        name: "Ubuntu 24.04.4 LTS Desktop",
        distro: "ubuntu",
        edition: "desktop-lts",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/24.04.4/ubuntu-24.04.4-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/noble/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 24.04.4 LTS Desktop (Noble) — autoinstall supported since 23.04",
    },
    IsoPreset {
        id: PresetId::UbuntuServer2510,
        name: "Ubuntu 25.10 Server",
        distro: "ubuntu",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/25.10/ubuntu-25.10-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/questing/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 25.10 Server (Questing) — non-LTS; cloud-init autoinstall",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktop2510,
        name: "Ubuntu 25.10 Desktop",
        distro: "ubuntu",
        edition: "desktop",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/25.10/ubuntu-25.10-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/questing/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 25.10 Desktop (Questing) — non-LTS",
    },
    IsoPreset {
        id: PresetId::UbuntuServerJammy,
        name: "Ubuntu 22.04.5 LTS Server",
        distro: "ubuntu",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/22.04.5/ubuntu-22.04.5-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/jammy/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 22.04.5 LTS Server (Jammy) — cloud-init autoinstall",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktopJammy,
        name: "Ubuntu 22.04.5 LTS Desktop",
        distro: "ubuntu",
        edition: "desktop",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/22.04.5/ubuntu-22.04.5-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/jammy/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 22.04.5 LTS Desktop (Jammy) — supported until April 2027",
    },
    IsoPreset {
        id: PresetId::UbuntuServerFocal,
        name: "Ubuntu 20.04.6 LTS Server",
        distro: "ubuntu",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/20.04.6/ubuntu-20.04.6-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/focal/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 20.04.6 LTS Server (Focal) — cloud-init autoinstall",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktopFocal,
        name: "Ubuntu 20.04.6 LTS Desktop",
        distro: "ubuntu",
        edition: "desktop",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/20.04.6/ubuntu-20.04.6-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/focal/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 20.04.6 LTS Desktop (Focal) — supported until April 2025",
    },
    IsoPreset {
        id: PresetId::UbuntuServerBionic,
        name: "Ubuntu 18.04.6 LTS Server",
        distro: "ubuntu",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/18.04.6/ubuntu-18.04.6-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/bionic/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 18.04.6 LTS Server (Bionic) — ESM only; legacy deployments",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktopBionic,
        name: "Ubuntu 18.04.6 LTS Desktop",
        distro: "ubuntu",
        edition: "desktop",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/18.04.6/ubuntu-18.04.6-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/bionic/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 18.04.6 LTS Desktop (Bionic) — ESM only; legacy deployments",
    },
    IsoPreset {
        id: PresetId::LinuxMintCinnamon,
        name: "Linux Mint 22.3 Cinnamon",
        distro: "mint",
        edition: "cinnamon",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://linuxmint.com/edition.php?id=326",
        direct_url: Some(
            "https://mirrors.edge.kernel.org/linuxmint/stable/22.3/linuxmint-22.3-cinnamon-64bit.iso",
        ),
        checksum_url: Some(
            "https://mirrors.edge.kernel.org/linuxmint/stable/22.3/sha256sum.txt",
        ),
        filename_suffix: Some("-cinnamon-64bit.iso"),
        note: "Linux Mint 22.3 Zena — Cinnamon desktop, Ubuntu 24.04 base",
    },
    IsoPreset {
        id: PresetId::LinuxMintMate,
        name: "Linux Mint 22.3 MATE",
        distro: "mint",
        edition: "mate",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://linuxmint.com/edition.php?id=327",
        direct_url: Some(
            "https://mirrors.edge.kernel.org/linuxmint/stable/22.3/linuxmint-22.3-mate-64bit.iso",
        ),
        checksum_url: Some(
            "https://mirrors.edge.kernel.org/linuxmint/stable/22.3/sha256sum.txt",
        ),
        filename_suffix: Some("-mate-64bit.iso"),
        note: "Linux Mint 22.3 Zena — MATE desktop, Ubuntu 24.04 base",
    },
    IsoPreset {
        id: PresetId::LinuxMintXfce,
        name: "Linux Mint 22.3 Xfce",
        distro: "mint",
        edition: "xfce",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://linuxmint.com/edition.php?id=328",
        direct_url: Some(
            "https://mirrors.edge.kernel.org/linuxmint/stable/22.3/linuxmint-22.3-xfce-64bit.iso",
        ),
        checksum_url: Some(
            "https://mirrors.edge.kernel.org/linuxmint/stable/22.3/sha256sum.txt",
        ),
        filename_suffix: Some("-xfce-64bit.iso"),
        note: "Linux Mint 22.3 Zena — Xfce desktop, Ubuntu 24.04 base",
    },
    IsoPreset {
        id: PresetId::FedoraServer,
        name: "Fedora 42 Server",
        distro: "fedora",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://fedoraproject.org/server/download/",
        direct_url: Some(
            "https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Server/x86_64/iso/Fedora-Server-netinst-x86_64-42-1.1.iso",
        ),
        checksum_url: Some(
            "https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Server/x86_64/iso/Fedora-Server-42-1.1-x86_64-CHECKSUM",
        ),
        filename_suffix: Some("-Server-netinst-x86_64-"),
        note: "Fedora 42 Server — network install; unattended via Kickstart",
    },
    IsoPreset {
        id: PresetId::FedoraWorkstation,
        name: "Fedora 42 Workstation",
        distro: "fedora",
        edition: "workstation",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://fedoraproject.org/workstation/download/",
        direct_url: Some(
            "https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Workstation/x86_64/iso/Fedora-Workstation-Live-42-1.1.x86_64.iso",
        ),
        checksum_url: Some(
            "https://dl.fedoraproject.org/pub/fedora/linux/releases/42/Workstation/x86_64/iso/Fedora-Workstation-42-1.1-x86_64-CHECKSUM",
        ),
        filename_suffix: Some("-Workstation-Live-"),
        note: "Fedora 42 Workstation — GNOME live image; Kickstart injection",
    },
    IsoPreset {
        id: PresetId::FedoraKde,
        name: "Fedora 42 KDE",
        distro: "fedora",
        edition: "kde",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://fedoraproject.org/spins/kde/download/",
        direct_url: Some(
            "https://dl.fedoraproject.org/pub/fedora/linux/releases/42/KDE/x86_64/iso/Fedora-KDE-Desktop-Live-42-1.1.x86_64.iso",
        ),
        checksum_url: Some(
            "https://dl.fedoraproject.org/pub/fedora/linux/releases/42/KDE/x86_64/iso/Fedora-KDE-42-1.1-x86_64-CHECKSUM",
        ),
        filename_suffix: Some("-KDE-Desktop-Live-"),
        note: "Fedora 42 KDE — Plasma desktop live spin",
    },
    IsoPreset {
        id: PresetId::RockyLinux,
        name: "Rocky Linux 9",
        distro: "rhel-family",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://rockylinux.org/download",
        // -latest- alias always tracks the current 9.x point release;
        // avoids URL rot on every minor bump (9.5 → 9.6 → 9.7 …).
        direct_url: Some(
            "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9-latest-x86_64-boot.iso",
        ),
        checksum_url: Some(
            "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/CHECKSUM",
        ),
        filename_suffix: Some("-x86_64-boot.iso"),
        note: "Rocky Linux 9 — RHEL-compatible; unattended via Kickstart (same path as Fedora)",
    },
    IsoPreset {
        id: PresetId::AlmaLinux,
        name: "AlmaLinux 9",
        distro: "rhel-family",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://almalinux.org/get-almalinux/",
        // -latest- alias always tracks the current 9.x point release;
        // avoids URL rot on every minor bump (9.5 → 9.6 → 9.7 …).
        direct_url: Some(
            "https://repo.almalinux.org/almalinux/9/isos/x86_64/AlmaLinux-9-latest-x86_64-boot.iso",
        ),
        checksum_url: Some(
            "https://repo.almalinux.org/almalinux/9/isos/x86_64/CHECKSUM",
        ),
        filename_suffix: Some("-x86_64-boot.iso"),
        note: "AlmaLinux 9 — RHEL-compatible; unattended via Kickstart",
    },
    IsoPreset {
        id: PresetId::CentOsStream,
        name: "CentOS Stream 10",
        distro: "rhel-family",
        edition: "stream",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://www.centos.org/download/",
        direct_url: Some(
            "https://mirror.stream.centos.org/10-stream/BaseOS/x86_64/iso/CentOS-Stream-10-latest-x86_64-boot.iso",
        ),
        checksum_url: None,
        filename_suffix: Some("-x86_64-boot.iso"),
        note: "CentOS Stream 10 — RHEL upstream; unattended via Kickstart",
    },
    IsoPreset {
        id: PresetId::ArchLinux,
        name: "Arch Linux",
        distro: "arch",
        edition: "rolling",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://archlinux.org/download/",
        direct_url: Some("https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso"),
        checksum_url: Some(
            "https://geo.mirror.pkgbuild.com/iso/latest/sha256sums.txt",
        ),
        filename_suffix: Some("archlinux-x86_64.iso"),
        note: "Arch Linux — archinstall config injection; see docs/distro-support.md",
    },
    IsoPreset {
        id: PresetId::EndeavourOs,
        name: "EndeavourOS",
        distro: "arch",
        edition: "endeavouros",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://endeavouros.com/latest-release/",
        direct_url: Some(
            "https://mirrors.tuna.tsinghua.edu.cn/endeavouros/iso/EndeavourOS_Ganymede-Neo-2026.01.12.iso",
        ),
        checksum_url: Some(
            "https://mirrors.tuna.tsinghua.edu.cn/endeavouros/iso/EndeavourOS_Ganymede-Neo-2026.01.12.iso.sha512sum",
        ),
        filename_suffix: Some("EndeavourOS_Ganymede-Neo-"),
        note: "EndeavourOS — Arch-based, friendly installer; TUNA mirror",
    },
    IsoPreset {
        id: PresetId::GarudaDr460nized,
        name: "Garuda Linux dr460nized",
        distro: "arch",
        edition: "dr460nized",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://garudalinux.org/downloads",
        direct_url: Some(
            "https://iso.builds.garudalinux.org/iso/garuda/dr460nized/260308/garuda-dr460nized-linux-zen-260308.iso",
        ),
        checksum_url: None,
        filename_suffix: Some("garuda-dr460nized-linux-zen-"),
        note: "Garuda dr460nized — KDE Plasma eye-candy; build-dated URL (update periodically)",
    },
    IsoPreset {
        id: PresetId::GarudaGnome,
        name: "Garuda Linux GNOME",
        distro: "arch",
        edition: "gnome",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://garudalinux.org/downloads",
        direct_url: Some(
            "https://iso.builds.garudalinux.org/iso/garuda/gnome/260308/garuda-gnome-linux-zen-260308.iso",
        ),
        checksum_url: None,
        filename_suffix: Some("garuda-gnome-linux-zen-"),
        note: "Garuda GNOME — Arch-based; build-dated URL (update periodically)",
    },
    IsoPreset {
        id: PresetId::GarudaXfce,
        name: "Garuda Linux Xfce",
        distro: "arch",
        edition: "xfce",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://garudalinux.org/downloads",
        direct_url: Some(
            "https://iso.builds.garudalinux.org/iso/garuda/xfce/260308/garuda-xfce-linux-lts-260308.iso",
        ),
        checksum_url: None,
        filename_suffix: Some("garuda-xfce-linux-lts-"),
        note: "Garuda Xfce — Arch-based, lightweight; build-dated URL (update periodically)",
    },
    IsoPreset {
        id: PresetId::Manjaro,
        name: "Manjaro",
        distro: "arch",
        edition: "kde",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DiscoveryPage,
        official_page: "https://manjaro.org/download/",
        direct_url: None,
        checksum_url: None,
        filename_suffix: Some("manjaro-kde-"),
        note: "Manjaro — filename includes kernel+build stamp; visit download page for current URL",
    },
    // ── Debian ───────────────────────────────────────────────────────────────
    IsoPreset {
        id: PresetId::DebianNetInst,
        name: "Debian 13.3.0 Netinstall",
        distro: "debian",
        edition: "netinstall",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://www.debian.org/CD/netinst/",
        direct_url: Some(
            "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.3.0-amd64-netinst.iso",
        ),
        checksum_url: Some(
            "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA256SUMS",
        ),
        filename_suffix: Some("-amd64-netinst.iso"),
        note: "Debian 13 (Trixie) — minimal netinstall; preseed unattended install",
    },
    // ── openSUSE — kernel.org mirror ─────────────────────────────────────────
    IsoPreset {
        id: PresetId::OpenSuseLeap,
        name: "openSUSE Leap 15.6 DVD",
        distro: "opensuse",
        edition: "leap-dvd",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://get.opensuse.org/leap/",
        direct_url: Some(
            "https://mirrors.kernel.org/opensuse/distribution/leap/15.6/iso/openSUSE-Leap-15.6-DVD-x86_64-Media.iso",
        ),
        checksum_url: Some(
            "https://mirrors.kernel.org/opensuse/distribution/leap/15.6/iso/openSUSE-Leap-15.6-DVD-x86_64-Media.iso.sha256",
        ),
        filename_suffix: Some("-DVD-x86_64-Media.iso"),
        note: "openSUSE Leap 15.6 — traditional LTS release; AutoYaST unattended install",
    },
    IsoPreset {
        id: PresetId::OpenSuseLeapNet,
        name: "openSUSE Leap 15.6 NET",
        distro: "opensuse",
        edition: "leap-net",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://get.opensuse.org/leap/",
        direct_url: Some(
            "https://mirrors.kernel.org/opensuse/distribution/leap/15.6/iso/openSUSE-Leap-15.6-NET-x86_64-Media.iso",
        ),
        checksum_url: Some(
            "https://mirrors.kernel.org/opensuse/distribution/leap/15.6/iso/openSUSE-Leap-15.6-NET-x86_64-Media.iso.sha256",
        ),
        filename_suffix: Some("-NET-x86_64-Media.iso"),
        note: "openSUSE Leap 15.6 — network installer; smaller download",
    },
    IsoPreset {
        id: PresetId::OpenSuseTumbleweed,
        name: "openSUSE Tumbleweed DVD",
        distro: "opensuse",
        edition: "tumbleweed",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://get.opensuse.org/tumbleweed/",
        direct_url: Some(
            "https://mirrors.kernel.org/opensuse/tumbleweed/iso/openSUSE-Tumbleweed-DVD-x86_64-Current.iso",
        ),
        checksum_url: Some(
            "https://mirrors.kernel.org/opensuse/tumbleweed/iso/openSUSE-Tumbleweed-DVD-x86_64-Current.iso.sha256",
        ),
        filename_suffix: Some("Tumbleweed-DVD-x86_64-Current.iso"),
        note: "openSUSE Tumbleweed — rolling release; Current alias always points to latest",
    },
    // ── Security ─────────────────────────────────────────────────────────────
    IsoPreset {
        id: PresetId::KaliLinux,
        name: "Kali Linux 2025.4 Installer",
        distro: "debian",
        edition: "kali",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://www.kali.org/get-kali/",
        direct_url: Some(
            "https://cdimage.kali.org/current/kali-linux-2025.4-installer-amd64.iso",
        ),
        checksum_url: Some("https://cdimage.kali.org/current/SHA256SUMS"),
        filename_suffix: Some("-installer-amd64.iso"),
        note: "Kali Linux 2025.4 — full installer; preseed supported",
    },
    IsoPreset {
        id: PresetId::KaliLinuxNetinst,
        name: "Kali Linux 2025.4 Netinstall",
        distro: "debian",
        edition: "kali-netinst",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://www.kali.org/get-kali/",
        direct_url: Some(
            "https://cdimage.kali.org/current/kali-linux-2025.4-installer-netinst-amd64.iso",
        ),
        checksum_url: Some("https://cdimage.kali.org/current/SHA256SUMS"),
        filename_suffix: Some("-installer-netinst-amd64.iso"),
        note: "Kali Linux 2025.4 — netinstall; minimal download, packages from network",
    },
    // ── Pop!_OS — iso.pop-os.org ──────────────────────────────────────────────
    IsoPreset {
        id: PresetId::PopOs22Intel,
        name: "Pop!_OS 22.04 (Intel/AMD)",
        distro: "ubuntu",
        edition: "pop-os-intel",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://pop.system76.com/",
        direct_url: Some(
            "https://iso.pop-os.org/22.04/amd64/intel/46/pop-os_22.04_amd64_intel_46.iso",
        ),
        checksum_url: Some(
            "https://iso.pop-os.org/22.04/amd64/intel/46/SHA256SUMS",
        ),
        filename_suffix: Some("_amd64_intel_"),
        note: "Pop!_OS 22.04 — Intel/AMD GPU build; Ubuntu 22.04 base",
    },
    IsoPreset {
        id: PresetId::PopOs22Nvidia,
        name: "Pop!_OS 22.04 (NVIDIA)",
        distro: "ubuntu",
        edition: "pop-os-nvidia",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://pop.system76.com/",
        direct_url: Some(
            "https://iso.pop-os.org/22.04/amd64/nvidia/46/pop-os_22.04_amd64_nvidia_46.iso",
        ),
        checksum_url: Some(
            "https://iso.pop-os.org/22.04/amd64/nvidia/46/SHA256SUMS",
        ),
        filename_suffix: Some("_amd64_nvidia_"),
        note: "Pop!_OS 22.04 — NVIDIA GPU build with proprietary drivers bundled",
    },
    IsoPreset {
        id: PresetId::PopOs24Intel,
        name: "Pop!_OS 24.04 (Intel/AMD)",
        distro: "ubuntu",
        edition: "pop-os-24-intel",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://pop.system76.com/",
        direct_url: Some(
            "https://iso.pop-os.org/24.04/amd64/intel/9/pop-os_24.04_amd64_intel_9.iso",
        ),
        checksum_url: Some(
            "https://iso.pop-os.org/24.04/amd64/intel/9/SHA256SUMS",
        ),
        filename_suffix: Some("_amd64_intel_"),
        note: "Pop!_OS 24.04 — Intel/AMD GPU build; Ubuntu 24.04 base",
    },
    IsoPreset {
        id: PresetId::RhelCustom,
        name: "RHEL (Custom)",
        distro: "rhel-family",
        edition: "custom",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::UserProvided,
        official_page: "https://access.redhat.com/downloads/",
        direct_url: None,
        checksum_url: None,
        filename_suffix: None,
        note: "RHEL requires a subscription. Provide a local ISO path or your own URL.",
    },
];
