use crate::autoinstall::{build_feature_late_commands, hash_password};
use crate::config::InjectConfig;
use crate::error::EngineResult;

/// Generate a Fedora/RHEL Kickstart configuration from InjectConfig.
///
/// The resulting `ks.cfg` content covers identity, network, packages, and a
/// `%post` section that reuses the same late-command logic as the Ubuntu
/// cloud-init path (NTP, groups, shell, sudo, services, sysctl, swap,
/// firewall, GRUB, mounts, run_commands, extra_late_commands).
pub fn generate_kickstart_cfg(cfg: &InjectConfig) -> EngineResult<String> {
    let mut lines: Vec<String> = Vec::new();

    // ── Header ───────────────────────────────────────────────────────────────
    lines.push("# Generated by ForgeISO".to_string());
    lines.push("text".to_string());

    // ── Locale / keyboard / timezone ─────────────────────────────────────────
    let locale = cfg.locale.as_deref().unwrap_or("en_US.UTF-8");
    lines.push(format!("lang {locale}"));

    let kb = cfg.keyboard_layout.as_deref().unwrap_or("us");
    lines.push(format!("keyboard {kb}"));

    let tz = cfg.timezone.as_deref().unwrap_or("UTC");
    lines.push(format!("timezone {tz} --utc"));

    // ── Root account (locked) ─────────────────────────────────────────────────
    lines.push("rootpw --lock".to_string());

    // ── User account ─────────────────────────────────────────────────────────
    if let Some(uname) = &cfg.username {
        let mut user_line = format!("user --name={uname}");
        if !cfg.user.groups.is_empty() {
            user_line.push_str(&format!(" --groups={}", cfg.user.groups.join(",")));
        }
        if let Some(pwd) = &cfg.password {
            let hashed = hash_password(pwd)?;
            user_line.push_str(&format!(" --password={hashed} --iscrypted"));
        }
        if let Some(realname) = &cfg.realname {
            user_line.push_str(&format!(" --gecos=\"{realname}\""));
        }
        lines.push(user_line);

        // SSH authorized keys (one sshkey directive per key)
        for key in &cfg.ssh.authorized_keys {
            let k = key.trim();
            if !k.is_empty() {
                lines.push(format!("sshkey --username={uname} \"{k}\""));
            }
        }
    }

    // ── Network ──────────────────────────────────────────────────────────────
    if let Some(static_ip) = &cfg.static_ip {
        // Parse CIDR notation: "10.0.0.5/24" → ip=10.0.0.5 netmask=255.255.255.0
        let (ip, mask) = parse_cidr(static_ip);
        let mut net_line = format!(
            "network --bootproto=static --device=link --onboot=on --ip={ip} --netmask={mask}"
        );
        if let Some(gw) = &cfg.gateway {
            net_line.push_str(&format!(" --gateway={gw}"));
        }
        if !cfg.network.dns_servers.is_empty() {
            net_line.push_str(&format!(
                " --nameserver={}",
                cfg.network.dns_servers.join(",")
            ));
        }
        lines.push(net_line);
    } else {
        let mut net_line = "network --bootproto=dhcp --device=link --onboot=on".to_string();
        if !cfg.network.dns_servers.is_empty() {
            net_line.push_str(&format!(
                " --nameserver={}",
                cfg.network.dns_servers.join(",")
            ));
        }
        lines.push(net_line);
    }

    // ── Hostname ─────────────────────────────────────────────────────────────
    if let Some(hostname) = &cfg.hostname {
        lines.push(format!("network --hostname={hostname}"));
    }

    // ── Storage layout ───────────────────────────────────────────────────────
    match cfg.storage_layout.as_deref() {
        Some("lvm") => {
            lines.push("autopart --type=lvm".to_string());
        }
        Some("zfs") => {
            // Kickstart doesn't natively support ZFS; fall back to lvm
            lines.push("autopart --type=lvm".to_string());
        }
        _ => {
            lines.push("autopart --type=plain".to_string());
        }
    }
    lines.push("clearpart --all --initlabel".to_string());

    // ── Reboot ───────────────────────────────────────────────────────────────
    lines.push("reboot".to_string());

    // ── Firewall (native Kickstart directive) ─────────────────────────────────
    // The `firewall` directive controls the initial firewalld state at install
    // time.  Fine-grained port rules are applied in %post via firewall-cmd.
    if cfg.firewall.enabled {
        lines.push("firewall --enabled".to_string());
    } else {
        lines.push("firewall --disabled".to_string());
    }

    // ── repo directives (DNF extra repos) ────────────────────────────────────
    // Each entry is either a plain https:// URL (we emit a dnf install command
    // in %post) or a [id]\nbaseurl=... stanza pasted verbatim.  URL-only entries
    // are handled below in %post; stanza entries go into a .repo file.
    // We emit nothing here in the header — dnf repos are consumed in %post.

    // ── %packages ─────────────────────────────────────────────────────────────
    lines.push(String::new());
    lines.push("%packages".to_string());
    lines.push("@^minimal-environment".to_string());
    if cfg.firewall.enabled {
        lines.push("firewalld".to_string());
    }
    for pkg in &cfg.extra_packages {
        lines.push(pkg.clone());
    }
    lines.push("%end".to_string());

    // ── %post ─────────────────────────────────────────────────────────────────
    let late_cmds = build_feature_late_commands(cfg)?;
    // Build DNF repo and mirror commands to prepend to %post
    let mut dnf_post: Vec<String> = Vec::new();

    // Override primary mirror if requested
    if let Some(mirror) = &cfg.dnf_mirror {
        // Write a custom .repo file that overrides the fedora + updates baseurl
        dnf_post.push(format!(
            r"sed -i 's|^baseurl=.*|baseurl={mirror}/$releasever/Everything/$basearch/os/|' /etc/yum.repos.d/fedora.repo 2>/dev/null || true"
        ));
        dnf_post.push(format!(
            r"sed -i 's|^baseurl=.*|baseurl={mirror}/$releasever/Everything/$basearch/os/|' /etc/yum.repos.d/fedora-updates.repo 2>/dev/null || true"
        ));
    }

    // Docker CE — uses the upstream Docker Inc. Fedora repository.
    if cfg.containers.docker {
        dnf_post.push("dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo 2>/dev/null || true".to_string());
        dnf_post.push("dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin 2>/dev/null || true".to_string());
        dnf_post.push("systemctl enable docker".to_string());
        for user in &cfg.containers.docker_users {
            dnf_post.push(format!("usermod -aG docker {user}"));
        }
    }

    // Podman — available from Fedora's standard repos (no extra repo needed).
    if cfg.containers.podman {
        dnf_post.push("dnf install -y podman 2>/dev/null || true".to_string());
    }

    // Install extra repos: URL entries → dnf install; stanza entries → write .repo file
    for (idx, repo) in cfg.dnf_repos.iter().enumerate() {
        let trimmed = repo.trim();
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with("https://") || trimmed.starts_with("http://") {
            // Plain URL — install the RPM or .repo file directly
            if trimmed.to_ascii_lowercase().ends_with(".rpm") {
                dnf_post.push(format!("dnf install -y '{trimmed}' 2>/dev/null || true"));
            } else {
                // Assume it's a .repo URL
                dnf_post.push(format!(
                    "dnf config-manager --add-repo '{trimmed}' 2>/dev/null || true"
                ));
            }
        } else {
            // Treat as a verbatim .repo stanza. Use a heredoc so multi-line
            // stanza content is written with real newlines — {stanza:?} would
            // use Debug formatting which escapes '\n' as two-char sequences,
            // producing a single-line .repo file that dnf cannot parse.
            let repo_name = format!("forgeiso-extra-{idx}");
            dnf_post.push(format!(
                "cat > /etc/yum.repos.d/{repo_name}.repo << 'FORGEISO_REPO_EOF'\n{stanza}\nFORGEISO_REPO_EOF",
                repo_name = repo_name,
                stanza = trimmed,
            ));
        }
    }

    // The last N commands from build_feature_late_commands are user-provided
    // (run_commands, extra_late_commands) and must pass through unchanged so
    // users can control their own paths (e.g. echo /data/target/file).
    // All preceding commands are engine-generated and MUST have /target/ paths
    // rewritten because %post runs inside the installed-system chroot where
    // there is no /target directory.
    let user_cmd_count = cfg.run_commands.len() + cfg.extra_late_commands.len();
    let generated_count = late_cmds.len().saturating_sub(user_cmd_count);

    let all_post: Vec<String> = dnf_post
        .into_iter()
        .chain(late_cmds.iter().enumerate().map(|(idx, cmd)| {
            if idx < generated_count {
                // Engine-generated command: rewrite all /target/ references.
                // chroot-prefixed form: strip the wrapper, then fix inner paths.
                // Direct /target/ form (NTP printf, echo, sed, fallocate, etc.):
                // replace the prefix component so the path is valid inside chroot.
                if let Some(inner) = cmd.strip_prefix("chroot /target ") {
                    inner.replace("/target/", "/").replace("/target ", "/ ")
                } else {
                    cmd.replace("/target/", "/")
                }
            } else {
                // User-provided (run_commands / extra_late_commands):
                // pass through unchanged.
                cmd.clone()
            }
        }))
        .collect();

    if !all_post.is_empty() {
        lines.push(String::new());
        lines.push("%post".to_string());
        for cmd in &all_post {
            lines.push(cmd.clone());
        }
        lines.push("%end".to_string());
    }

    Ok(lines.join("\n") + "\n")
}

/// Parse a CIDR address string (e.g. "10.0.0.5/24") into (ip, netmask).
/// Falls back to (addr, "255.255.255.0") if the prefix is missing or invalid.
pub(crate) fn parse_cidr(cidr: &str) -> (String, String) {
    if let Some((ip, prefix)) = cidr.split_once('/') {
        let mask = prefix_to_mask(prefix.parse::<u8>().unwrap_or(24));
        (ip.to_string(), mask)
    } else {
        (cidr.to_string(), "255.255.255.0".to_string())
    }
}

fn prefix_to_mask(prefix: u8) -> String {
    let bits = if prefix >= 32 {
        0xFFFF_FFFFu32
    } else {
        !(0xFFFF_FFFFu32 >> prefix)
    };
    format!(
        "{}.{}.{}.{}",
        (bits >> 24) & 0xFF,
        (bits >> 16) & 0xFF,
        (bits >> 8) & 0xFF,
        bits & 0xFF
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{InjectConfig, IsoSource};

    fn base_cfg() -> InjectConfig {
        InjectConfig {
            source: IsoSource::from_raw("/tmp/fedora.iso"),
            out_name: "out.iso".to_string(),
            ..Default::default()
        }
    }

    #[test]
    fn test_kickstart_minimal() {
        let cfg = base_cfg();
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("# Generated by ForgeISO"));
        assert!(ks.contains("rootpw --lock"));
        assert!(ks.contains("reboot"));
        assert!(ks.contains("%packages"));
        assert!(ks.contains("%end"));
    }

    #[test]
    fn test_kickstart_with_user() {
        let mut cfg = base_cfg();
        cfg.username = Some("admin".to_string());
        cfg.password = Some("secret".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("user --name=admin"));
        assert!(ks.contains("--iscrypted"));
    }

    #[test]
    fn test_kickstart_with_static_ip() {
        let mut cfg = base_cfg();
        cfg.static_ip = Some("10.0.0.5/24".to_string());
        cfg.gateway = Some("10.0.0.1".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("--bootproto=static"));
        assert!(ks.contains("--ip=10.0.0.5"));
        assert!(ks.contains("--netmask=255.255.255.0"));
        assert!(ks.contains("--gateway=10.0.0.1"));
    }

    #[test]
    fn test_kickstart_packages() {
        let mut cfg = base_cfg();
        cfg.extra_packages = vec!["curl".to_string(), "git".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("curl"));
        assert!(ks.contains("git"));
    }

    #[test]
    fn test_cidr_parsing() {
        assert_eq!(
            parse_cidr("192.168.1.10/24"),
            ("192.168.1.10".to_string(), "255.255.255.0".to_string())
        );
        assert_eq!(
            parse_cidr("10.0.0.1/16"),
            ("10.0.0.1".to_string(), "255.255.0.0".to_string())
        );
    }

    #[test]
    fn test_kickstart_with_dnf_mirror() {
        let mut cfg = base_cfg();
        cfg.dnf_mirror = Some("https://mirror.example.com/fedora".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // dnf_mirror should appear in the generated kickstart
        assert!(
            ks.contains("mirror.example.com"),
            "dnf_mirror not found in kickstart: {ks}"
        );
    }

    #[test]
    fn test_kickstart_post_section_with_commands() {
        // %post is only emitted when there are late commands
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["echo hello".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // With run_commands, %post must be present
        assert!(
            ks.contains("%post"),
            "no %post section in kickstart when run_commands present"
        );
        assert!(ks.contains("%end"), "no %end after %post");
        assert!(ks.contains("echo hello"), "run_command missing from %post");
    }

    #[test]
    fn test_kickstart_services() {
        let mut cfg = base_cfg();
        cfg.enable_services = vec!["sshd".to_string(), "docker".to_string()];
        cfg.disable_services = vec!["firewalld".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // Services are emitted via systemctl in %post (not the Kickstart `services`
        // directive); each service generates its own line.
        assert!(
            ks.contains("systemctl enable sshd"),
            "enable sshd not found in kickstart %post: {ks}"
        );
        assert!(
            ks.contains("systemctl enable docker"),
            "enable docker not found in kickstart %post: {ks}"
        );
        assert!(
            ks.contains("systemctl disable firewalld"),
            "disable firewalld not found in kickstart %post: {ks}"
        );
    }

    #[test]
    fn test_kickstart_rpm_url_uppercase_extension() {
        // Regression: .RPM (uppercase) must be installed with `dnf install`,
        // NOT added as a repo with `dnf config-manager --add-repo`.
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["https://example.com/package.RPM".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("dnf install -y 'https://example.com/package.RPM'"),
            "uppercase .RPM URL must use 'dnf install', not 'dnf config-manager': {ks}"
        );
        assert!(
            !ks.contains("config-manager"),
            "uppercase .RPM URL must not use dnf config-manager: {ks}"
        );
    }

    #[test]
    fn test_kickstart_repo_url_install() {
        // Plain .rpm URLs should use dnf install
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["https://example.com/package.rpm".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("dnf install"),
            "rpm URL should use dnf install: {ks}"
        );
    }

    #[test]
    fn test_kickstart_repo_stanza_inline() {
        // Non-URL entries should be written as .repo stanza content
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["[myrepo]\nbaseurl=https://example.com/repo\nenabled=1".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("forgeiso-extra-0.repo") || ks.contains("myrepo"),
            "repo stanza should be written to a file: {ks}"
        );
    }

    #[test]
    fn test_repo_stanza_written_with_real_newlines() {
        // Regression: {stanza:?} (Debug formatting) was used, which escapes \n
        // as two-char sequences. The .repo file would then contain literal \n
        // characters instead of newlines, making the file unparseable by dnf.
        // Fix: use a heredoc so newlines are preserved verbatim.
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["[myrepo]\nbaseurl=https://example.com/repo\nenabled=1".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // The heredoc sentinel must appear as a line in %post
        assert!(
            ks.contains("FORGEISO_REPO_EOF"),
            "heredoc sentinel not found — stanza not written via heredoc: {ks}"
        );
        // The stanza body must appear verbatim (not as an escaped string)
        assert!(
            ks.contains("[myrepo]"),
            "repo stanza section header missing from kickstart: {ks}"
        );
        assert!(
            ks.contains("baseurl=https://example.com/repo"),
            "repo baseurl missing from kickstart: {ks}"
        );
        // Must NOT contain the debug-formatted backslash-n literal
        assert!(
            !ks.contains(r"[myrepo]\nbaseurl"),
            "stanza written with Debug-escaped \\n instead of real newlines: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_does_not_corrupt_bare_commands() {
        // A bare echo/printf command that happens to contain the substring
        // "/target" in a path literal must NOT be altered by the chroot
        // transformer (regression for the unwrap_or bug).
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["echo /data/target/file".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // The path must survive unchanged — only "chroot /target " prefix
        // commands are rewritten.
        assert!(
            ks.contains("/data/target/file"),
            "bare command with /target literal was incorrectly transformed: {ks}"
        );
        // And it must NOT appear without the /data prefix
        assert!(
            !ks.contains("echo /data//file"),
            "path was double-collapsed: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_rewrites_chroot_commands() {
        // Engine-generated "chroot /target ..." commands must be stripped of
        // their prefix with /target/ references resolved to /.
        // We trigger the transformer via enable_services which generates
        // "chroot /target systemctl enable sshd".
        let mut cfg = base_cfg();
        cfg.enable_services = vec!["sshd".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // chroot prefix removed; command appears directly in %post
        assert!(
            ks.contains("systemctl enable sshd"),
            "chroot command was not correctly stripped: {ks}"
        );
        // The "chroot /target " prefix must be absent
        assert!(
            !ks.contains("chroot /target systemctl enable sshd"),
            "chroot prefix not removed from generated service command: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_user_run_commands_untouched() {
        // User-provided run_commands must pass through unchanged even when they
        // contain /target path literals — the user controls their own paths and
        // may have intentional /target/ references in their scripts.
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["echo /data/target/archive.tar.gz".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("echo /data/target/archive.tar.gz"),
            "user run_command path was incorrectly rewritten: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_ntp_no_target_prefix_in_kickstart() {
        // Regression: NTP late-command writes to /target/etc/systemd/timesyncd.conf
        // in the cloud-init form.  In Kickstart %post (which runs inside the chroot),
        // that path must be rewritten to /etc/systemd/timesyncd.conf.
        let mut cfg = base_cfg();
        cfg.network = crate::config::NetworkConfig {
            ntp_servers: vec!["time.cloudflare.com".to_string()],
            dns_servers: vec![],
        };
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            !ks.contains("/target/etc/systemd/timesyncd.conf"),
            "NTP command still contains /target/ prefix in Kickstart output: {ks}"
        );
        assert!(
            ks.contains("/etc/systemd/timesyncd.conf"),
            "NTP config path missing from Kickstart %post: {ks}"
        );
        assert!(
            ks.contains("time.cloudflare.com"),
            "NTP server missing from Kickstart %post: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_proxy_no_target_prefix_in_kickstart() {
        // Regression: proxy late-commands write to /target/etc/environment.
        // In Kickstart %post, that path must be /etc/environment.
        let mut cfg = base_cfg();
        cfg.proxy = crate::config::ProxyConfig {
            http_proxy: Some("http://proxy.corp:3128".to_string()),
            https_proxy: None,
            no_proxy: vec![],
        };
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            !ks.contains("/target/etc/environment"),
            "proxy command still contains /target/ in Kickstart output: {ks}"
        );
        assert!(
            ks.contains("/etc/environment"),
            "proxy config path missing from Kickstart %post: {ks}"
        );
        assert!(
            ks.contains("http_proxy"),
            "http_proxy missing from Kickstart %post: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_sysctl_no_target_prefix_in_kickstart() {
        // Regression: sysctl late-commands write to /target/etc/sysctl.d/...
        // In Kickstart %post that path must be /etc/sysctl.d/...
        let mut cfg = base_cfg();
        cfg.sysctl = vec![("net.ipv4.ip_forward".to_string(), "1".to_string())];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            !ks.contains("/target/etc/sysctl.d"),
            "sysctl command still contains /target/ prefix in Kickstart output: {ks}"
        );
        assert!(
            ks.contains("/etc/sysctl.d/99-forgeiso.conf"),
            "sysctl config path missing from Kickstart %post: {ks}"
        );
    }

    #[test]
    fn test_kickstart_grub_uses_grub2_mkconfig_not_update_grub() {
        // Regression: build_feature_late_commands emitted "chroot /target update-grub"
        // unconditionally.  update-grub is a Debian/Ubuntu wrapper that does not exist
        // on Fedora.  For Fedora Kickstart %post, the correct command is
        // grub2-mkconfig -o /boot/grub2/grub.cfg.
        let mut cfg = base_cfg();
        cfg.distro = Some(crate::config::Distro::Fedora);
        cfg.grub = crate::config::GrubConfig {
            timeout: Some(5),
            cmdline_extra: vec![],
            default_entry: None,
        };
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("grub2-mkconfig"),
            "Fedora kickstart must use grub2-mkconfig, not update-grub: {ks}"
        );
        assert!(
            !ks.contains("update-grub"),
            "update-grub must not appear in Fedora kickstart (Debian-only): {ks}"
        );
    }

    #[test]
    fn test_post_transformer_grub_sed_no_target_prefix_in_kickstart() {
        // Regression: GRUB late-commands use `sed -i '...' /target/etc/default/grub`.
        // In Kickstart %post the path must be /etc/default/grub.
        let mut cfg = base_cfg();
        cfg.grub = crate::config::GrubConfig {
            timeout: Some(5),
            cmdline_extra: vec![],
            default_entry: None,
        };
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            !ks.contains("/target/etc/default/grub"),
            "GRUB sed command still contains /target/ prefix in Kickstart output: {ks}"
        );
        assert!(
            ks.contains("/etc/default/grub"),
            "GRUB config path missing from Kickstart %post: {ks}"
        );
    }
}
