use crate::autoinstall::{build_feature_late_commands, hash_password};
use crate::config::InjectConfig;
use crate::error::EngineResult;

/// Generate a Fedora/RHEL Kickstart configuration from InjectConfig.
///
/// The resulting `ks.cfg` content covers identity, network, packages, and a
/// `%post` section that reuses the same late-command logic as the Ubuntu
/// cloud-init path (NTP, groups, shell, sudo, services, sysctl, swap,
/// firewall, GRUB, mounts, run_commands, extra_late_commands).
pub fn generate_kickstart_cfg(cfg: &InjectConfig) -> EngineResult<String> {
    let mut lines: Vec<String> = Vec::new();

    // ── Header ───────────────────────────────────────────────────────────────
    lines.push("# Generated by ForgeISO".to_string());
    lines.push("text".to_string());

    // ── Locale / keyboard / timezone ─────────────────────────────────────────
    let locale = cfg.locale.as_deref().unwrap_or("en_US.UTF-8");
    lines.push(format!("lang {locale}"));

    let kb = cfg.keyboard_layout.as_deref().unwrap_or("us");
    lines.push(format!("keyboard {kb}"));

    let tz = cfg.timezone.as_deref().unwrap_or("UTC");
    lines.push(format!("timezone {tz} --utc"));

    // ── Root account (locked) ─────────────────────────────────────────────────
    lines.push("rootpw --lock".to_string());

    // ── User account ─────────────────────────────────────────────────────────
    if let Some(uname) = &cfg.username {
        let mut user_line = format!("user --name={uname}");
        if !cfg.user.groups.is_empty() {
            user_line.push_str(&format!(" --groups={}", cfg.user.groups.join(",")));
        }
        if let Some(pwd) = &cfg.password {
            let hashed = hash_password(pwd)?;
            user_line.push_str(&format!(" --password={hashed} --iscrypted"));
        }
        if let Some(realname) = &cfg.realname {
            user_line.push_str(&format!(" --gecos=\"{realname}\""));
        }
        lines.push(user_line);

        // SSH authorized keys (one sshkey directive per key)
        for key in &cfg.ssh.authorized_keys {
            let k = key.trim();
            if !k.is_empty() {
                lines.push(format!("sshkey --username={uname} \"{k}\""));
            }
        }
    }

    // ── Network ──────────────────────────────────────────────────────────────
    if let Some(static_ip) = &cfg.static_ip {
        // Parse CIDR notation: "10.0.0.5/24" → ip=10.0.0.5 netmask=255.255.255.0
        let (ip, mask) = parse_cidr(static_ip);
        let mut net_line = format!(
            "network --bootproto=static --device=link --onboot=on --ip={ip} --netmask={mask}"
        );
        if let Some(gw) = &cfg.gateway {
            net_line.push_str(&format!(" --gateway={gw}"));
        }
        if !cfg.network.dns_servers.is_empty() {
            net_line.push_str(&format!(
                " --nameserver={}",
                cfg.network.dns_servers.join(",")
            ));
        }
        lines.push(net_line);
    } else {
        let mut net_line = "network --bootproto=dhcp --device=link --onboot=on".to_string();
        if !cfg.network.dns_servers.is_empty() {
            net_line.push_str(&format!(
                " --nameserver={}",
                cfg.network.dns_servers.join(",")
            ));
        }
        lines.push(net_line);
    }

    // ── Hostname ─────────────────────────────────────────────────────────────
    if let Some(hostname) = &cfg.hostname {
        lines.push(format!("network --hostname={hostname}"));
    }

    // ── Storage layout ───────────────────────────────────────────────────────
    match cfg.storage_layout.as_deref() {
        Some("lvm") => {
            lines.push("autopart --type=lvm".to_string());
        }
        Some("zfs") => {
            // Kickstart doesn't natively support ZFS; fall back to lvm
            lines.push("autopart --type=lvm".to_string());
        }
        _ => {
            lines.push("autopart --type=plain".to_string());
        }
    }
    lines.push("clearpart --all --initlabel".to_string());

    // ── Reboot ───────────────────────────────────────────────────────────────
    lines.push("reboot".to_string());

    // ── Firewall (native Kickstart directive) ─────────────────────────────────
    // The `firewall` directive controls the initial firewalld state at install
    // time.  Fine-grained port rules are applied in %post via firewall-cmd.
    if cfg.firewall.enabled {
        lines.push("firewall --enabled".to_string());
    } else {
        lines.push("firewall --disabled".to_string());
    }

    // ── repo directives (DNF extra repos) ────────────────────────────────────
    // Each entry is either a plain https:// URL (we emit a dnf install command
    // in %post) or a [id]\nbaseurl=... stanza pasted verbatim.  URL-only entries
    // are handled below in %post; stanza entries go into a .repo file.
    // We emit nothing here in the header — dnf repos are consumed in %post.

    // ── %packages ─────────────────────────────────────────────────────────────
    lines.push(String::new());
    lines.push("%packages".to_string());
    lines.push("@^minimal-environment".to_string());
    if cfg.firewall.enabled {
        lines.push("firewalld".to_string());
    }
    for pkg in &cfg.extra_packages {
        lines.push(pkg.clone());
    }
    lines.push("%end".to_string());

    // ── %post ─────────────────────────────────────────────────────────────────
    let late_cmds = build_feature_late_commands(cfg)?;
    // Build DNF repo and mirror commands to prepend to %post
    let mut dnf_post: Vec<String> = Vec::new();

    // Override primary mirror if requested
    if let Some(mirror) = &cfg.dnf_mirror {
        // Write a custom .repo file that overrides the fedora + updates baseurl
        dnf_post.push(format!(
            r"sed -i 's|^baseurl=.*|baseurl={mirror}/$releasever/Everything/$basearch/os/|' /etc/yum.repos.d/fedora.repo 2>/dev/null || true"
        ));
        dnf_post.push(format!(
            r"sed -i 's|^baseurl=.*|baseurl={mirror}/$releasever/Everything/$basearch/os/|' /etc/yum.repos.d/fedora-updates.repo 2>/dev/null || true"
        ));
    }

    // Docker CE — uses the upstream Docker Inc. Fedora repository.
    if cfg.containers.docker {
        dnf_post.push("dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo 2>/dev/null || true".to_string());
        dnf_post.push("dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin 2>/dev/null || true".to_string());
        dnf_post.push("systemctl enable docker".to_string());
        for user in &cfg.containers.docker_users {
            dnf_post.push(format!("usermod -aG docker {user}"));
        }
    }

    // Podman — available from Fedora's standard repos (no extra repo needed).
    if cfg.containers.podman {
        dnf_post.push("dnf install -y podman 2>/dev/null || true".to_string());
    }

    // Install extra repos: URL entries → dnf install; stanza entries → write .repo file
    for (idx, repo) in cfg.dnf_repos.iter().enumerate() {
        let trimmed = repo.trim();
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with("https://") || trimmed.starts_with("http://") {
            // Plain URL — install the RPM or .repo file directly
            if trimmed.to_ascii_lowercase().ends_with(".rpm") {
                dnf_post.push(format!("dnf install -y '{trimmed}' 2>/dev/null || true"));
            } else {
                // Assume it's a .repo URL
                dnf_post.push(format!(
                    "dnf config-manager --add-repo '{trimmed}' 2>/dev/null || true"
                ));
            }
        } else {
            // Treat as a verbatim .repo stanza
            let repo_name = format!("forgeiso-extra-{idx}");
            dnf_post.push(format!(
                "printf '%s\\n' {stanza:?} > /etc/yum.repos.d/{repo_name}.repo",
                stanza = trimmed,
                repo_name = repo_name,
            ));
        }
    }

    let all_post: Vec<String> = dnf_post
        .into_iter()
        .chain(late_cmds.iter().map(|cmd| {
            // Only transform commands that explicitly address the chroot target.
            // Bare commands (mkdir, echo, printf stanzas) must pass through
            // unchanged to avoid corrupting path literals that happen to contain
            // the substring "/target".
            if let Some(inner) = cmd.strip_prefix("chroot /target ") {
                inner.replace("/target/", "/").replace("/target ", "/ ")
            } else {
                cmd.clone()
            }
        }))
        .collect();

    if !all_post.is_empty() {
        lines.push(String::new());
        lines.push("%post".to_string());
        for cmd in &all_post {
            lines.push(cmd.clone());
        }
        lines.push("%end".to_string());
    }

    Ok(lines.join("\n") + "\n")
}

/// Parse a CIDR address string (e.g. "10.0.0.5/24") into (ip, netmask).
/// Falls back to (addr, "255.255.255.0") if the prefix is missing or invalid.
pub(crate) fn parse_cidr(cidr: &str) -> (String, String) {
    if let Some((ip, prefix)) = cidr.split_once('/') {
        let mask = prefix_to_mask(prefix.parse::<u8>().unwrap_or(24));
        (ip.to_string(), mask)
    } else {
        (cidr.to_string(), "255.255.255.0".to_string())
    }
}

fn prefix_to_mask(prefix: u8) -> String {
    let bits = if prefix >= 32 {
        0xFFFF_FFFFu32
    } else {
        !(0xFFFF_FFFFu32 >> prefix)
    };
    format!(
        "{}.{}.{}.{}",
        (bits >> 24) & 0xFF,
        (bits >> 16) & 0xFF,
        (bits >> 8) & 0xFF,
        bits & 0xFF
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{InjectConfig, IsoSource};

    fn base_cfg() -> InjectConfig {
        InjectConfig {
            source: IsoSource::from_raw("/tmp/fedora.iso"),
            out_name: "out.iso".to_string(),
            ..Default::default()
        }
    }

    #[test]
    fn test_kickstart_minimal() {
        let cfg = base_cfg();
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("# Generated by ForgeISO"));
        assert!(ks.contains("rootpw --lock"));
        assert!(ks.contains("reboot"));
        assert!(ks.contains("%packages"));
        assert!(ks.contains("%end"));
    }

    #[test]
    fn test_kickstart_with_user() {
        let mut cfg = base_cfg();
        cfg.username = Some("admin".to_string());
        cfg.password = Some("secret".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("user --name=admin"));
        assert!(ks.contains("--iscrypted"));
    }

    #[test]
    fn test_kickstart_with_static_ip() {
        let mut cfg = base_cfg();
        cfg.static_ip = Some("10.0.0.5/24".to_string());
        cfg.gateway = Some("10.0.0.1".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("--bootproto=static"));
        assert!(ks.contains("--ip=10.0.0.5"));
        assert!(ks.contains("--netmask=255.255.255.0"));
        assert!(ks.contains("--gateway=10.0.0.1"));
    }

    #[test]
    fn test_kickstart_packages() {
        let mut cfg = base_cfg();
        cfg.extra_packages = vec!["curl".to_string(), "git".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(ks.contains("curl"));
        assert!(ks.contains("git"));
    }

    #[test]
    fn test_cidr_parsing() {
        assert_eq!(
            parse_cidr("192.168.1.10/24"),
            ("192.168.1.10".to_string(), "255.255.255.0".to_string())
        );
        assert_eq!(
            parse_cidr("10.0.0.1/16"),
            ("10.0.0.1".to_string(), "255.255.0.0".to_string())
        );
    }

    #[test]
    fn test_kickstart_with_dnf_mirror() {
        let mut cfg = base_cfg();
        cfg.dnf_mirror = Some("https://mirror.example.com/fedora".to_string());
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // dnf_mirror should appear in the generated kickstart
        assert!(
            ks.contains("mirror.example.com"),
            "dnf_mirror not found in kickstart: {ks}"
        );
    }

    #[test]
    fn test_kickstart_post_section_with_commands() {
        // %post is only emitted when there are late commands
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["echo hello".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // With run_commands, %post must be present
        assert!(
            ks.contains("%post"),
            "no %post section in kickstart when run_commands present"
        );
        assert!(ks.contains("%end"), "no %end after %post");
        assert!(ks.contains("echo hello"), "run_command missing from %post");
    }

    #[test]
    fn test_kickstart_services() {
        let mut cfg = base_cfg();
        cfg.enable_services = vec!["sshd".to_string(), "docker".to_string()];
        cfg.disable_services = vec!["firewalld".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("services --enabled=sshd,docker")
                || ks.contains("sshd") && ks.contains("docker"),
            "enabled services not found in kickstart: {ks}"
        );
    }

    #[test]
    fn test_kickstart_rpm_url_uppercase_extension() {
        // Regression: .RPM (uppercase) must install the same as .rpm
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["https://example.com/package.RPM".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("dnf install") || ks.contains("package.RPM"),
            "uppercase .RPM URL not handled: {ks}"
        );
    }

    #[test]
    fn test_kickstart_repo_url_install() {
        // Plain .rpm URLs should use dnf install
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["https://example.com/package.rpm".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("dnf install"),
            "rpm URL should use dnf install: {ks}"
        );
    }

    #[test]
    fn test_kickstart_repo_stanza_inline() {
        // Non-URL entries should be written as .repo stanza content
        let mut cfg = base_cfg();
        cfg.dnf_repos = vec!["[myrepo]\nbaseurl=https://example.com/repo\nenabled=1".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        assert!(
            ks.contains("forgeiso-extra-0.repo") || ks.contains("myrepo"),
            "repo stanza should be written to a file: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_does_not_corrupt_bare_commands() {
        // A bare echo/printf command that happens to contain the substring
        // "/target" in a path literal must NOT be altered by the chroot
        // transformer (regression for the unwrap_or bug).
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["echo /data/target/file".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // The path must survive unchanged — only "chroot /target " prefix
        // commands are rewritten.
        assert!(
            ks.contains("/data/target/file"),
            "bare command with /target literal was incorrectly transformed: {ks}"
        );
        // And it must NOT appear without the /data prefix
        assert!(
            !ks.contains("echo /data//file"),
            "path was double-collapsed: {ks}"
        );
    }

    #[test]
    fn test_post_transformer_rewrites_chroot_commands() {
        // A "chroot /target ..." command must be stripped of its prefix and
        // any remaining /target/ references resolved to /.
        let mut cfg = base_cfg();
        cfg.run_commands = vec!["chroot /target touch /target/etc/resolv.conf".to_string()];
        let ks = generate_kickstart_cfg(&cfg).unwrap();
        // chroot prefix removed; /target/ collapsed to /
        assert!(
            ks.contains("touch /etc/resolv.conf"),
            "chroot command was not correctly stripped: {ks}"
        );
    }
}
