//! Ubuntu LTS + interim presets sourced from `mirror.xenyth.net/ubuntu-releases`.

use super::super::preset::IsoPreset;
use super::super::preset_id::PresetId;
use super::super::strategy::AcquisitionStrategy;

pub(super) static PRESETS: &[IsoPreset] = &[
    IsoPreset {
        id: PresetId::UbuntuServerLts,
        name: "Ubuntu 24.04.4 LTS Server",
        distro: "ubuntu",
        edition: "server-lts",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/24.04.4/ubuntu-24.04.4-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/noble/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 24.04.4 LTS Server (Noble) — unattended via cloud-init autoinstall",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktopLts,
        name: "Ubuntu 24.04.4 LTS Desktop",
        distro: "ubuntu",
        edition: "desktop-lts",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/24.04.4/ubuntu-24.04.4-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/noble/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 24.04.4 LTS Desktop (Noble) — autoinstall supported since 23.04",
    },
    IsoPreset {
        id: PresetId::UbuntuServer2510,
        name: "Ubuntu 25.10 Server",
        distro: "ubuntu",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/25.10/ubuntu-25.10-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/questing/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 25.10 Server (Questing) — non-LTS; cloud-init autoinstall",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktop2510,
        name: "Ubuntu 25.10 Desktop",
        distro: "ubuntu",
        edition: "desktop",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/25.10/ubuntu-25.10-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/questing/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 25.10 Desktop (Questing) — non-LTS",
    },
    IsoPreset {
        id: PresetId::UbuntuServerJammy,
        name: "Ubuntu 22.04.5 LTS Server",
        distro: "ubuntu",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/22.04.5/ubuntu-22.04.5-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/jammy/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 22.04.5 LTS Server (Jammy) — cloud-init autoinstall",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktopJammy,
        name: "Ubuntu 22.04.5 LTS Desktop",
        distro: "ubuntu",
        edition: "desktop",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/22.04.5/ubuntu-22.04.5-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/jammy/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 22.04.5 LTS Desktop (Jammy) — supported until April 2027",
    },
    IsoPreset {
        id: PresetId::UbuntuServerFocal,
        name: "Ubuntu 20.04.6 LTS Server",
        distro: "ubuntu",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/20.04.6/ubuntu-20.04.6-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/focal/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 20.04.6 LTS Server (Focal) — cloud-init autoinstall",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktopFocal,
        name: "Ubuntu 20.04.6 LTS Desktop",
        distro: "ubuntu",
        edition: "desktop",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/20.04.6/ubuntu-20.04.6-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/focal/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 20.04.6 LTS Desktop (Focal) — supported until April 2025",
    },
    IsoPreset {
        id: PresetId::UbuntuServerBionic,
        name: "Ubuntu 18.04.6 LTS Server",
        distro: "ubuntu",
        edition: "server",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/server",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/18.04.6/ubuntu-18.04.6-live-server-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/bionic/SHA256SUMS"),
        filename_suffix: Some("-live-server-amd64.iso"),
        note: "Ubuntu 18.04.6 LTS Server (Bionic) — ESM only; legacy deployments",
    },
    IsoPreset {
        id: PresetId::UbuntuDesktopBionic,
        name: "Ubuntu 18.04.6 LTS Desktop",
        distro: "ubuntu",
        edition: "desktop",
        architecture: "x86_64",
        strategy: AcquisitionStrategy::DirectUrl,
        official_page: "https://ubuntu.com/download/desktop",
        direct_url: Some(
            "https://mirror.xenyth.net/ubuntu-releases/18.04.6/ubuntu-18.04.6-desktop-amd64.iso",
        ),
        checksum_url: Some("https://releases.ubuntu.com/bionic/SHA256SUMS"),
        filename_suffix: Some("-desktop-amd64.iso"),
        note: "Ubuntu 18.04.6 LTS Desktop (Bionic) — ESM only; legacy deployments",
    },
];
